language: python
sudo: true
dist: trusty
os: linux
python:
  - "3.5"

install:
  - travis_wait pip install -r requirements.txt || date
  - travis_wait pip install -r test-requirements.txt || date
  - pip install codecov pytest-cov flake8
script:
  - flake8 .
  - pytest --cov=jade
after_success:
  - codecov
group: stable
notifications:
  irc:
    channels:
      - "chat.freenode.net#wikimedia-ai"
    on_success: change
    on_failure: change
    template:
      - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} %{build_url}"
